"use client";
import { useState } from "react";
import { FlaskConical, RefreshCw, ShieldAlert } from "lucide-react";
import type { BacktestResult } from "@/lib/backtesting";
import type { MarketAsset, Timeframe } from "@/lib/market-data";

export function BacktestWorkspace({ asset }: { asset: MarketAsset }) {
  const [timeframe, setTimeframe] = useState<Exclude<Timeframe, "1D">>("15m"); const [minimumConfidence, setMinimumConfidence] = useState(60); const [stopAtr, setStopAtr] = useState(1); const [targetAtr, setTargetAtr] = useState(2); const [maximumHoldCandles, setMaximumHoldCandles] = useState(12); const [feesBps, setFeesBps] = useState(5); const [slippageBps, setSlippageBps] = useState(3); const [result, setResult] = useState<BacktestResult | null>(null); const [provider, setProvider] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const run = async () => { setLoading(true); setError(""); try { const response = await fetch("/api/backtest", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ symbol: asset.symbol, category: asset.category, timeframe, minimumConfidence, stopAtr, targetAtr, maximumHoldCandles, feesBps, slippageBps }) }); const body = await response.json() as { ok: boolean; data: BacktestResult | null; provider?: string; message?: string }; if (!response.ok || !body.ok || !body.data) throw new Error(body.message ?? "Backtest failed"); setResult(body.data); setProvider(body.provider ?? "Market provider"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Backtest failed"); } finally { setLoading(false); } };
  return <div className="mt-5"><section className="border border-blue-500/20 bg-blue-500/[.04] p-3 sm:p-4"><div className="flex items-start gap-2"><FlaskConical size={16} className="mt-0.5 shrink-0 text-blue-400"/><div><b className="text-[11px] tracking-wider text-white">CLOSED-CANDLE PATTERN BACKTEST · {asset.symbol}</b><p className="mt-1 text-[9px] leading-4 text-[#8993a1]">No future structure is leaked into signals. Entry is the next candle open; if stop and target are both touched, the stop is counted first.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Select label="TIMEFRAME" value={timeframe} onChange={(value) => setTimeframe(value as typeof timeframe)} options={["15m", "1H", "4H"]}/><NumberField label="MIN CONFIDENCE" value={minimumConfidence} onChange={setMinimumConfidence} min={40} max={95}/><NumberField label="STOP · ATR" value={stopAtr} onChange={setStopAtr} min={.25} max={5} step={.25}/><NumberField label="TARGET · ATR" value={targetAtr} onChange={setTargetAtr} min={.5} max={10} step={.25}/><NumberField label="MAX HOLD CANDLES" value={maximumHoldCandles} onChange={setMaximumHoldCandles} min={1} max={40}/><NumberField label="FEES · BPS" value={feesBps} onChange={setFeesBps} min={0} max={100}/><NumberField label="SLIPPAGE · BPS" value={slippageBps} onChange={setSlippageBps} min={0} max={100}/></div><button onClick={() => void run()} disabled={loading || asset.dataStatus === "UNAVAILABLE"} className="mt-4 flex h-10 w-full items-center justify-center gap-2 bg-blue-600 text-[10px] font-bold text-white disabled:opacity-40"><RefreshCw size={13} className={loading ? "animate-spin" : ""}/>{loading ? "REPLAYING HISTORICAL CANDLES…" : "RUN BACKTEST"}</button>{error && <div className="mt-3 text-[10px] text-red-300">{error}</div>}</section>{result && <BacktestReport result={result} provider={provider}/>}</div>;
}
function BacktestReport({ result, provider }: { result: BacktestResult; provider: string }) { const metrics = result.metrics; return <div className="mt-4 space-y-4"><div className="grid grid-cols-2 gap-px bg-[#252b35] sm:grid-cols-4 lg:grid-cols-7"><Metric label="TRADES" value={`${metrics.trades}`}/><Metric label="WIN RATE" value={`${metrics.winRate}%`}/><Metric label="PROFIT FACTOR" value={metrics.profitFactor === null ? "∞" : `${metrics.profitFactor}`}/><Metric label="EXPECTANCY" value={`${metrics.expectancyR > 0 ? "+" : ""}${metrics.expectancyR}R`} tone={metrics.expectancyR >= 0 ? "good" : "bad"}/><Metric label="NET RESULT" value={`${metrics.netR > 0 ? "+" : ""}${metrics.netR}R`} tone={metrics.netR >= 0 ? "good" : "bad"}/><Metric label="MAX DRAWDOWN" value={`${metrics.maximumDrawdownR}R`} tone="bad"/><Metric label="CANDLES" value={`${result.candles}`}/></div>{result.warning && <div className="flex gap-2 border border-amber-500/20 bg-amber-500/[.05] p-3 text-[9px] text-amber-200"><ShieldAlert size={13} className="shrink-0"/>{result.warning}</div>}<Breakdown title="BY PATTERN" rows={result.byPattern}/><Breakdown title="BY SESSION" rows={result.bySession}/><div className="text-[8px] text-[#596170]">{provider} · {result.signals} signals · Fees and slippage included · Generated {new Date(result.generatedAt).toLocaleString()}</div></div>; }
function Breakdown({ title, rows }: { title: string; rows: BacktestResult["byPattern"] }) { return <section className="overflow-x-auto border border-[#252b35]"><div className="border-b border-[#252b35] px-3 py-2 text-[9px] font-bold tracking-widest text-[#8993a1]">{title}</div><div className="grid min-w-[560px] grid-cols-[1.5fr_repeat(4,.7fr)] px-3 py-2 text-[8px] text-[#596170]"><span>NAME</span><span>TRADES</span><span>WINS</span><span>WIN RATE</span><span>EXPECTANCY</span></div>{rows.length ? rows.map((row) => <div key={row.name} className="grid min-w-[560px] grid-cols-[1.5fr_repeat(4,.7fr)] border-t border-[#1b2028] px-3 py-2 text-[9px]"><b>{row.name}</b><span>{row.trades}</span><span>{row.wins}</span><span>{row.winRate}%</span><span className={row.expectancyR >= 0 ? "text-emerald-400" : "text-red-400"}>{row.expectancyR}R</span></div>) : <div className="p-5 text-center text-[9px] text-[#687180]">No qualifying trades. Lower confidence or test another timeframe.</div>}</section>; }
function Metric({ label, value, tone }: { label: string; value: string; tone?: "good" | "bad" }) { return <div className="bg-[#0c1016] p-3"><span className="text-[8px] text-[#687180]">{label}</span><b className={`mt-1 block text-sm ${tone === "good" ? "text-emerald-400" : tone === "bad" ? "text-red-400" : "text-white"}`}>{value}</b></div>; }
function NumberField({ label, value, onChange, min, max, step = 1 }: { label: string; value: number; onChange: (value: number) => void; min: number; max: number; step?: number }) { return <label className="text-[8px] text-[#687180]">{label}<input type="number" value={value} min={min} max={max} step={step} onChange={(event) => onChange(Number(event.target.value))} className="mt-1 h-9 w-full border border-[#303744] bg-[#090c11] px-2 text-white outline-none focus:border-blue-500"/></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="text-[8px] text-[#687180]">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 h-9 w-full border border-[#303744] bg-[#090c11] px-2 text-white outline-none">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
