"use client";
import { useState } from "react";
import type { AIHistoryEntry } from "@/lib/ai";
import type { SymbolNewsContext } from "@/lib/news";
import { MarketNewsPanel } from "./MarketNewsPanel";
import type { BuyAlertRecord } from "@/lib/alerts/buy-alert-engine";
const tabs = ["Market News", "Alerts", "AI History", "Journal", "Scanner"] as const;
export function BottomPanel({ history = [], newsContext = null, alerts = [] }: { history?: AIHistoryEntry[]; newsContext?: SymbolNewsContext | null; alerts?: BuyAlertRecord[] }) {
  const [active, setActive] = useState<(typeof tabs)[number]>("Market News");
  return <section className="h-[178px] shrink-0 border-t border-[#20242d] bg-[#0b0e13]"><div className="flex h-9 items-center border-b border-[#20242d]">{tabs.map((tab) => <button key={tab} onClick={() => setActive(tab)} className={`h-9 border-b-2 px-4 text-[10px] font-semibold ${active === tab ? "border-blue-500 text-blue-400" : "border-transparent text-[#687180] hover:text-[#b6bdc8]"}`}>{tab}</button>)}</div>
    {active === "Market News" ? <div className="overflow-x-auto"><MarketNewsPanel context={newsContext}/></div> : active === "Alerts" && alerts.length ? <AlertHistory rows={alerts}/> : active === "AI History" && history.length ? <div className="overflow-x-auto"><div className="grid min-w-[760px] grid-cols-[1fr_.75fr_.75fr_.65fr_1fr_1.3fr] border-b border-[#191d24] px-4 py-2 text-[8px] uppercase tracking-wider text-[#4f5867]"><span>Symbol</span><span>Preference</span><span>Technical</span><span>News</span><span>Price</span><span>Analyzed</span></div>{history.slice(0, 3).map((entry) => <div key={`${entry.timestamp}-${entry.symbol}`} className="grid min-w-[760px] grid-cols-[1fr_.75fr_.75fr_.65fr_1fr_1.3fr] border-b border-[#171b22] px-4 py-2 font-mono text-[9px] text-[#aab1bd]"><span className="font-sans text-white">{entry.symbol}</span><span className={entry.preference === "BUY" ? "text-[#16c784]" : entry.preference === "SELL" ? "text-[#ea3943]" : "text-amber-400"}>{entry.preference} {entry.setupScore}</span><span>{entry.technicalPreference} {entry.technicalSetupScore}</span><span className={entry.newsRisk.label === "high" ? "text-red-400" : entry.newsRisk.label === "medium" ? "text-amber-400" : "text-blue-400"}>{entry.newsRisk.label.toUpperCase()}</span><span>{entry.price}</span><span>{new Date(entry.timestamp).toLocaleString()}</span></div>)}</div> : <div className="grid h-[130px] place-items-center"><div className="text-center"><div className="text-[11px] text-[#727b89]">No {active.toLowerCase()} items</div><div className="mt-1 text-[9px] text-[#424a57]">This analysis-only workspace does not execute trades</div></div></div>}
  </section>;
}
function AlertHistory({ rows }: { rows: BuyAlertRecord[] }) { return <div className="overflow-x-auto"><div className="grid min-w-[850px] grid-cols-[1fr_.7fr_.6fr_.7fr_.7fr_.8fr_1.2fr] border-b border-[#191d24] px-4 py-2 text-[8px] uppercase text-[#4f5867]"><span>Symbol</span><span>Status</span><span>Buy/Sell</span><span>Price</span><span>R:R</span><span>15M</span><span>Triggered</span></div>{rows.slice(0, 3).map((row) => <div key={row.id} className="grid min-w-[850px] grid-cols-[1fr_.7fr_.6fr_.7fr_.7fr_.8fr_1.2fr] border-b border-[#171b22] px-4 py-2 font-mono text-[9px]"><span className="font-sans font-bold text-[#16c784]">{row.symbol}</span><span>{row.status}</span><span>{row.buyScore}/{row.sellScore}</span><span>{row.price}</span><span>1:{row.riskReward.toFixed(2)}</span><span>{row.pattern ?? row.confirmation15M}</span><span>{new Date(row.timestamp).toLocaleString()}</span></div>)}</div>; }
