"use client";
import { BellRing, ShieldAlert, X } from "lucide-react";
import type { MarketCategory } from "@/lib/market-data/types";
import type { ReturnTypeUseBuyAlerts } from "./buy-alert-types";

const markets: MarketCategory[] = ["Forex", "Stocks", "Futures", "Crypto", "Meme Coins"];
export function BuyAlertSettingsPanel({ alerts, open, onClose }: { alerts: ReturnTypeUseBuyAlerts; open: boolean; onClose: () => void }) {
  if (!open) return null;
  const { settings } = alerts;
  return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/65 p-4"><section className="w-full max-w-lg border border-[#303744] bg-[#10151c] shadow-2xl"><header className="flex h-11 items-center border-b border-[#2a303b] px-4"><BellRing size={14} className="mr-2 text-blue-400"/><b className="text-[10px] tracking-widest">AI BUY ALERT SETTINGS</b><button onClick={onClose} className="ml-auto"><X size={14}/></button></header><div className="space-y-4 p-4 text-[9px]">
    <Toggle label="Enable Buy Alerts" value={settings.enabled} onChange={alerts.setEnabled}/>
    <label className="block text-[#8993a1]">ALERT FREQUENCY<select value={settings.frequency} onChange={(event) => alerts.setFrequency(event.target.value as typeof settings.frequency)} className="mt-1 h-9 w-full border border-[#2a303b] bg-[#090c11] px-2 text-white"><option value="conservative">Conservative</option><option value="balanced">Balanced</option><option value="aggressive">Aggressive</option></select></label>
    <div className="grid grid-cols-2 gap-3"><NumberSetting label="MINIMUM BUY SCORE" value={settings.minimumBuyScore} min={50} max={100} step={1} onChange={(minimumBuyScore) => alerts.updateSettings({ minimumBuyScore })}/><NumberSetting label="MINIMUM R:R" value={settings.minimumRiskReward} min={1} max={5} step={.1} onChange={(minimumRiskReward) => alerts.updateSettings({ minimumRiskReward })}/></div>
    <Toggle label="Require closed 15M confirmation" value={settings.requireConfirmation} onChange={(requireConfirmation) => alerts.updateSettings({ requireConfirmation })}/><Toggle label="Block during high news risk" value={settings.blockHighNewsRisk} onChange={(blockHighNewsRisk) => alerts.updateSettings({ blockHighNewsRisk })}/>
    <div><div className="mb-2 text-[#8993a1]">MONITORED MARKETS</div><div className="flex flex-wrap gap-2">{markets.map((market) => { const active = settings.markets.includes(market); return <button key={market} onClick={() => alerts.updateSettings({ markets: active ? settings.markets.filter((item) => item !== market) : [...settings.markets, market] })} className={`border px-2 py-1 ${active ? "border-blue-500/60 bg-blue-500/10 text-blue-300" : "border-[#303744] text-[#687180]"}`}>{market}</button>; })}</div></div>
    <div className="flex gap-2 border border-amber-500/20 bg-amber-500/5 p-3 text-amber-200"><ShieldAlert size={14} className="shrink-0"/><span>Alerts identify calculated setups only. They do not place orders and do not guarantee profit.</span></div>
  </div></section></div>;
}
export function BuyAlertToast({ alerts, onView }: { alerts: ReturnTypeUseBuyAlerts; onView: () => void }) { const item = alerts.toast; if (!item) return null; return <div className="fixed right-5 top-20 z-[90] w-80 border border-emerald-500/40 bg-[#0d1715] p-4 shadow-2xl"><div className="flex"><BellRing size={15} className="mr-2 text-[#16c784]"/><div><b className="text-[10px] tracking-widest text-[#16c784]">BUY SETUP DETECTED</b><div className="mt-1 text-sm font-bold text-white">{item.symbol}</div><div className="mt-1 text-[9px] text-[#aab4b0]">{item.quality} • Score {item.buyScore} • R:R 1:{item.riskReward.toFixed(2)}</div></div></div><div className="mt-3 flex gap-2"><button onClick={() => { alerts.viewAlert(item.id); onView(); }} className="bg-emerald-600 px-3 py-1.5 text-[8px] font-bold text-white">VIEW CHART</button><button onClick={alerts.dismissToast} className="border border-[#34413e] px-3 py-1.5 text-[8px]">DISMISS</button></div><div className="mt-2 text-[7px] text-[#6f7d79]">Trading setup alert — not guaranteed profit.</div></div>; }
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void | Promise<void> }) { return <label className="flex items-center justify-between"><span>{label}</span><button onClick={() => void onChange(!value)} className={`h-5 w-9 rounded-full p-0.5 ${value ? "bg-blue-600" : "bg-[#303744]"}`}><span className={`block size-4 rounded-full bg-white transition-transform ${value ? "translate-x-4" : ""}`}/></button></label>; }
function NumberSetting({ label, value, min, max, step, onChange }: { label: string; value: number; min: number; max: number; step: number; onChange: (value: number) => void }) { return <label className="text-[#8993a1]">{label}<input type="number" value={value} min={min} max={max} step={step} onChange={(event) => onChange(Number(event.target.value))} className="mt-1 h-9 w-full border border-[#2a303b] bg-[#090c11] px-2 text-white"/></label>; }
