"use client";
import Link from "next/link";
import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, BellRing, CheckCircle2, RefreshCw, ShieldAlert, Sparkles } from "lucide-react";
import type { MarketScanCandidate, MarketScanResult } from "@/lib/ai/market-scanner";
import type { PaperPosition } from "@/lib/positions/monitor";

async function getScan(): Promise<MarketScanResult> {
  const response = await fetch("/api/ai/scan");
  const body = await response.json() as { ok: boolean; data: MarketScanResult | null; message?: string };
  if (!response.ok || !body.ok || !body.data) throw new Error(body.message ?? "Market scan unavailable");
  return body.data;
}

export function RecommendedBuysPage() {
  const scan = useQuery({ queryKey: ["all-market-ai-scan"], queryFn: getScan, staleTime: 60_000 });
  const result = scan.data;
  const telegram = useQuery({ queryKey: ["telegram-status"], queryFn: async () => { const response = await fetch("/api/telegram/test"); return response.json() as Promise<{ ok: boolean; configured: boolean }>; }, staleTime: 30_000 });
  const positions = useQuery({ queryKey: ["paper-positions"], queryFn: async () => { const response = await fetch("/api/positions"); const body = await response.json() as { data: PaperPosition[] }; return body.data; }, refetchInterval: 10_000 });
  const buys = result?.candidates.filter((candidate) => candidate.preference === "BUY") ?? [];
  const preferred = buys.find((candidate) => candidate.symbol === result?.preferredSymbol) ?? null;
  return <main className="min-h-dvh bg-[#080a0e] text-[#d9dee7]">
    <header className="flex h-16 items-center border-b border-[#20242d] bg-[#0c0f14] px-5"><Link href="/" className="flex items-center gap-2 text-[11px] text-[#8993a1] hover:text-white"><ArrowLeft size={15}/> Trading workspace</Link><div className="mx-auto flex items-center gap-2"><span className="grid size-8 place-items-center bg-blue-600 text-xs font-black">AI</span><b className="text-sm tracking-wider">RECOMMENDED BUYS</b></div><button onClick={() => void scan.refetch()} disabled={scan.isFetching} className="grid size-9 place-items-center border border-[#303744] text-[#8993a1]"><RefreshCw size={15} className={scan.isFetching ? "animate-spin" : ""}/></button></header>
    <div className="mx-auto max-w-6xl p-5 md:p-8">
      <div className="mb-6"><div className="flex items-center gap-2 text-[10px] font-bold tracking-[.18em] text-blue-400"><Sparkles size={14}/> LIVE INTRADAY OPPORTUNITY SCAN</div><h1 className="mt-2 text-2xl font-black text-white md:text-3xl">What could we buy right now?</h1><p className="mt-2 text-[12px] text-[#8993a1]">Every configured market is checked on 15M, 1H, and 4H data. OpenAI prefers among setups that already passed the technical and risk gates.</p></div>
      <TelegramStatus configured={telegram.data?.configured ?? false}/>
      <ActivePositions positions={positions.data ?? []}/>
      {scan.isLoading ? <ScanLoading/> : scan.isError ? <div className="border border-red-500/30 bg-red-500/10 p-6 text-red-300">{(scan.error as Error).message}</div> : preferred ? <div className="space-y-6"><PreferredBuy candidate={preferred} result={result!}/>{buys.filter((candidate) => candidate.symbol !== preferred.symbol).map((candidate, index) => <QualifiedBuy key={candidate.symbol} candidate={candidate} rank={index + 2}/>)}</div> : <NoBuy result={result}/>} 
      {result && <AllMarketResults candidates={result.candidates}/>} 
      {result && <div className="mt-8 border-t border-[#20242d] pt-4 text-[10px] text-[#687180]">Last scan: {new Date(result.generatedAt).toLocaleTimeString()} · {result.scanned} available markets checked · {result.unavailable} unavailable · Refreshes at most once per minute</div>}
    </div>
  </main>;
}

function PreferredBuy({ candidate, result }: { candidate: MarketScanCandidate; result: MarketScanResult }) {
  return <RecommendationShell candidate={candidate} rank={1} rationale={result.rationale} preferred><TradeTicket candidate={candidate}/></RecommendationShell>;
}
function QualifiedBuy({ candidate, rank }: { candidate: MarketScanCandidate; rank: number }) {
  const rationale = [...candidate.ruleReasons, ...candidate.ruleWarnings].slice(0, 3).join(" ");
  return <RecommendationShell candidate={candidate} rank={rank} rationale={rationale || "This setup passed the intraday BUY and risk gates."}><TradeTicket candidate={candidate}/></RecommendationShell>;
}
function RecommendationShell({ candidate, rank, rationale, preferred = false, children }: { candidate: MarketScanCandidate; rank: number; rationale: string; preferred?: boolean; children: React.ReactNode }) {
  const highlyRecommended = candidate.setupScore >= 80;
  return <section className={`border p-5 md:p-7 ${highlyRecommended ? "border-emerald-400/60 bg-emerald-500/[.07]" : "border-blue-500/40 bg-blue-500/[.05]"}`}><div className="flex flex-wrap items-start gap-4"><div><div className={`flex items-center gap-2 text-[10px] font-bold tracking-[.18em] ${highlyRecommended ? "text-emerald-400" : "text-blue-400"}`}><CheckCircle2 size={14}/> #{rank} · {highlyRecommended ? "HIGHLY RECOMMENDED" : "RECOMMENDED"}{preferred ? " · AI TOP PICK" : ""}</div><div className={`mt-2 text-3xl font-black md:text-5xl ${highlyRecommended ? "text-emerald-400" : "text-blue-400"}`}>{highlyRecommended ? "STRONG BUY" : "BUY"}</div><div className="mt-2 text-xl font-bold text-white">{candidate.symbol} <span className="text-sm font-normal text-[#8993a1]">· {candidate.name}</span></div></div><div className="ml-auto grid grid-cols-2 gap-px bg-[#2b3540]"><Metric label="SCORE" value={`${candidate.setupScore}/100`}/><Metric label="RISK / REWARD" value={`1:${candidate.riskReward.ratio?.toFixed(2) ?? "—"}`}/><Metric label="15M" value={candidate.confirmation15M.confirmed ? "CONFIRMED" : "MISSING"}/><Metric label="MARKET" value={candidate.category}/></div></div><div className="mt-6 border border-[#2a3b38] bg-[#09110f] p-4"><b className="text-[10px] tracking-widest text-[#8993a1]">WHY IT QUALIFIED</b><p className="mt-2 text-[12px] leading-6 text-[#c5d0cd]">{rationale}</p></div>{children}<div className="mt-4 flex items-start gap-2 text-[10px] leading-5 text-amber-300"><ShieldAlert size={14} className="mt-0.5 shrink-0"/>Time-sensitive paper setup, not a guarantee. Recheck the exact symbol and live Ask before submitting.</div></section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="min-w-32 bg-[#0c1312] p-3"><div className="text-[9px] font-bold tracking-wider text-[#687180]">{label}</div><b className="mt-1 block text-[12px] text-white">{value}</b></div>; }
function TradeTicket({ candidate }: { candidate: MarketScanCandidate }) {
  const queryClient = useQueryClient();
  const [tracking, setTracking] = useState(false);
  const [trackMessage, setTrackMessage] = useState("");
  const [balance, setBalance] = useState(100000);
  const [riskPercent, setRiskPercent] = useState(1);
  const [leverage, setLeverage] = useState(10);
  const { entry, stop, target } = candidate.riskReward;
  const distance = entry && stop ? Math.abs(entry - stop) : 0;
  const rewardDistance = entry && target ? Math.abs(target - entry) : 0;
  const riskAmount = Math.max(0, balance * riskPercent / 100);
  const riskUnits = distance > 0 ? riskAmount / distance : 0;
  const leverageUnits = entry > 0 ? balance * leverage / entry : 0;
  const rawUnits = Math.max(0, Math.min(riskUnits, leverageUnits));
  const allowsFractionalUnits = candidate.category === "Crypto" || candidate.category === "Meme Coins";
  const unitPrecision = allowsFractionalUnits ? 8 : 0;
  const unitFactor = 10 ** unitPrecision;
  const suggestedUnits = Math.floor(rawUnits * unitFactor) / unitFactor;
  const plannedRisk = suggestedUnits * distance;
  const plannedReward = suggestedUnits * rewardDistance;
  const decimals = candidate.category === "Forex" ? (candidate.symbol.includes("JPY") ? 3 : 5) : entry >= 1000 ? 2 : entry >= 1 ? 4 : 8;
  const price = (value: number | null) => value == null ? "—" : value.toLocaleString("en-US", { minimumFractionDigits: decimals, maximumFractionDigits: decimals });
  const tradingViewSymbol = candidate.category === "Crypto" || candidate.category === "Meme Coins" ? `BINANCE:${candidate.symbol.replace("/", "")}` : candidate.category === "Forex" ? `FX:${candidate.symbol.replace("/", "")}` : candidate.symbol;
  return <section className="mt-5 overflow-hidden border border-blue-500/40 bg-[#0c0d10]"><div className="flex flex-wrap items-center gap-2 border-b border-[#292d35] px-4 py-3"><b className="text-[11px] tracking-widest text-white">AI PREFERRED TRADINGVIEW SETTINGS</b><span className="ml-auto border border-blue-500/30 bg-blue-500/10 px-2 py-1 text-[9px] font-bold text-blue-400">PAPER TRADE</span></div>
    <div className="p-4 md:p-5"><div className="border border-amber-500/30 bg-amber-500/[.06] p-3"><div className="text-[9px] font-bold tracking-widest text-amber-300">OPEN THIS EXACT SYMBOL</div><div className="mt-1 font-mono text-lg font-bold text-white">{tradingViewSymbol}</div><p className="mt-1 text-[10px] text-[#a9b0bc]">Do not substitute `{candidate.symbol.split("/")[0]}USD` from another exchange; its quote and candles can differ.</p></div>
    <div className="mt-4 grid gap-px bg-[#2c323c] sm:grid-cols-3"><TicketValue label="SIDE" value="BUY / LONG" tone="text-blue-400"/><TicketValue label="ORDER TYPE" value="LIMIT" tone="text-white"/><TicketValue label="TIME IN FORCE" value="DAY" tone="text-white"/></div>
    <div className="mt-3 grid gap-px bg-[#2c323c] sm:grid-cols-3"><TicketValue label="LIMIT PRICE" value={price(entry)} tone="text-blue-400"/><TicketValue label="TAKE PROFIT · ON" value={price(target)} tone="text-emerald-400"/><TicketValue label="STOP LOSS · ON" value={price(stop)} tone="text-red-400"/></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-3"><NumberInput label="PAPER ACCOUNT BALANCE" value={balance} onChange={setBalance}/><NumberInput label="MAX RISK %" value={riskPercent} onChange={setRiskPercent} step={.1}/><NumberInput label="PAPER LEVERAGE" value={leverage} onChange={setLeverage}/></div>
    <div className="mt-4 grid gap-px bg-[#2c323c] sm:grid-cols-4"><TicketValue label="UNITS" value={suggestedUnits ? suggestedUnits.toLocaleString(undefined, { maximumFractionDigits: unitPrecision }) : "Not available"} tone="text-white"/><TicketValue label="TRADE VALUE" value={(suggestedUnits * entry).toLocaleString(undefined, { maximumFractionDigits: 2 })} tone="text-white"/><TicketValue label="RISK AT SL" value={plannedRisk.toLocaleString(undefined, { maximumFractionDigits: 2 })} tone="text-red-300"/><TicketValue label="PROFIT AT TP" value={plannedReward.toLocaleString(undefined, { maximumFractionDigits: 2 })} tone="text-emerald-300"/></div>
    <div className="mt-4 border-l-2 border-blue-500 bg-blue-500/[.06] p-3 text-[10px] leading-5 text-[#aeb7c5]"><b className="text-white">Why these settings:</b> Limit controls the entry price; DAY prevents an intraday idea lingering indefinitely; paired TP and SL automatically close the paper position at the calculated target or invalidation. If the live Ask has moved materially away from {price(entry)}, refresh the scan instead of chasing it.</div>
    <button disabled={tracking || !suggestedUnits || stop == null || target == null} onClick={async () => { setTracking(true); setTrackMessage(""); try { const response = await fetch("/api/positions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ symbol: candidate.symbol, category: candidate.category, entry, stop, target, units: suggestedUnits }) }); const body = await response.json() as { ok: boolean; message?: string }; if (!response.ok || !body.ok) throw new Error(body.message ?? "Could not start tracking"); setTrackMessage("Paper position is now tracked. Telegram will alert when it is time to exit."); await queryClient.invalidateQueries({ queryKey: ["paper-positions"] }); } catch (error) { setTrackMessage(error instanceof Error ? error.message : "Could not start tracking"); } finally { setTracking(false); } }} className="mt-4 w-full bg-emerald-600 py-3 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{tracking ? "STARTING TRACKER…" : "I BOUGHT THIS — TRACK MY EXIT"}</button>{!suggestedUnits && <div className="mt-2 text-center text-[10px] text-amber-300">Increase the paper balance or reduce the risk distance to calculate a valid position size.</div>}{trackMessage && <div className="mt-2 text-center text-[10px] text-emerald-300">{trackMessage}</div>}</div>
    <div className="border-t border-[#292d35] bg-[#111318] p-3 text-[10px] text-amber-300">Copy these values into TradingView manually. This app does not submit the order. Keep one-click trading off so TradingView shows its confirmation preview.</div>
  </section>;
}
function TicketValue({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="bg-[#0b1118] p-3"><span className="text-[9px] font-bold tracking-wider text-[#687180]">{label}</span><b className={`mt-1 block font-mono text-base ${tone}`}>{value}</b></div>; }
function NumberInput({ label, value, onChange, step = 1 }: { label: string; value: number; onChange: (value: number) => void; step?: number }) { return <label className="text-[9px] font-bold tracking-wider text-[#687180]">{label}<input type="number" min="0" step={step} value={value} onChange={(event) => onChange(Math.max(0, Number(event.target.value)))} className="mt-1 h-9 w-full border border-[#303a46] bg-[#090d12] px-2 text-[11px] text-white outline-none focus:border-blue-500"/></label>; }
function TelegramStatus({ configured }: { configured: boolean }) { const [message, setMessage] = useState(""); return <section className={`mb-5 border p-4 ${configured ? "border-blue-500/30 bg-blue-500/[.05]" : "border-amber-500/30 bg-amber-500/[.05]"}`}><div className="flex items-center gap-2"><BellRing size={15} className={configured ? "text-blue-400" : "text-amber-400"}/><b className="text-[11px] tracking-widest">TELEGRAM EXIT ALERTS</b><span className={`ml-auto text-[10px] font-bold ${configured ? "text-emerald-400" : "text-amber-400"}`}>{configured ? "CONFIGURED" : "SETUP REQUIRED"}</span></div>{configured ? <button onClick={async () => { const response = await fetch("/api/telegram/test", { method: "POST" }); const body = await response.json() as { ok: boolean; message?: string }; setMessage(body.ok ? "Test alert sent to Telegram." : (body.message ?? "Test failed")); }} className="mt-3 border border-blue-500/40 px-3 py-2 text-[10px] font-bold text-blue-400">SEND TEST ALERT</button> : <p className="mt-2 text-[10px] leading-5 text-[#aeb6c2]">Create a bot with @BotFather, message the bot once, then add <code className="text-white">TELEGRAM_BOT_TOKEN</code> and <code className="text-white">TELEGRAM_CHAT_ID</code> to <code className="text-white">.env</code>. Never paste the bot token into the website or chat.</p>}{message && <span className="ml-3 text-[10px] text-[#aeb6c2]">{message}</span>}</section>; }
function ActivePositions({ positions }: { positions: PaperPosition[] }) { const queryClient = useQueryClient(); const active = positions.filter((position) => position.status !== "CLOSED"); if (!active.length) return null; return <section className="mb-5 border border-[#303744] bg-[#0c1016] p-4"><b className="text-[11px] tracking-widest">TRACKED PAPER POSITIONS</b><div className="mt-3 space-y-2">{active.map((position) => <div key={position.id} className={`grid items-center gap-3 border p-3 sm:grid-cols-[1fr_auto_auto] ${position.status === "EXIT_ALERTED" ? "border-red-500/50 bg-red-500/10" : "border-[#28313d]"}`}><div><b className={position.status === "EXIT_ALERTED" ? "text-red-400" : "text-emerald-400"}>{position.status === "EXIT_ALERTED" ? "SELL / EXIT NOW" : "TRACKING"} · {position.symbol}</b><div className="mt-1 text-[10px] text-[#8993a1]">Entry {position.entry} · Last {position.lastPrice} · SL {position.stop} · TP {position.target} · {position.units} units</div>{position.exitReason && <div className="mt-1 text-[10px] text-red-300">{position.exitReason}</div>}</div><span className="text-[9px] text-[#687180]">Checked {new Date(position.lastCheckedAt).toLocaleTimeString()}</span><button onClick={async () => { await fetch("/api/positions", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: position.id }) }); await queryClient.invalidateQueries({ queryKey: ["paper-positions"] }); }} className="border border-[#39424e] px-3 py-2 text-[9px] font-bold">MARK CLOSED</button></div>)}</div></section>; }
function AllMarketResults({ candidates }: { candidates: MarketScanCandidate[] }) {
  return <section className="mt-8 border border-[#252b34] bg-[#0b0e13] p-4"><div className="flex items-end gap-3"><div><h2 className="text-sm font-black tracking-wider text-white">ALL SCANNED MARKETS</h2><p className="mt-1 text-[10px] text-[#8993a1]">Score measures setup strength. A recommendation also requires every entry, confirmation, and risk gate to pass.</p></div><span className="ml-auto text-[10px] text-[#687180]">{candidates.length} markets</span></div><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{candidates.map((candidate) => { const buy = candidate.preference === "BUY"; const high = buy && candidate.setupScore >= 80; const invalidLongTarget = candidate.riskReward.target != null && candidate.riskReward.target <= candidate.riskReward.entry; const blockedReason = invalidLongTarget ? "Take-profit is below the entry, so there is no valid LONG trade plan" : !candidate.riskReward.valid ? candidate.riskReward.reason : !candidate.confirmation15M.confirmed ? "15M entry confirmation is missing" : candidate.ruleWarnings[0] ?? "A required BUY gate has not passed"; return <div key={`${candidate.category}-${candidate.symbol}`} className={`border p-3 ${high ? "border-emerald-500/40 bg-emerald-500/[.06]" : buy ? "border-blue-500/35 bg-blue-500/[.05]" : "border-[#252b34] bg-[#090c10]"}`}><div className="flex items-center gap-2"><b className="text-[12px] text-white">{candidate.symbol}</b><span className={`ml-auto text-[9px] font-black ${high ? "text-emerald-400" : buy ? "text-blue-400" : "text-amber-400"}`}>{high ? "HIGHLY RECOMMENDED" : buy ? "RECOMMENDED" : "WAIT"}</span></div><div className="mt-2 flex gap-3 text-[9px] text-[#8993a1]"><span>{candidate.category}</span><span>Score {candidate.setupScore}/100</span><span>R:R {candidate.riskReward.ratio ? `1:${candidate.riskReward.ratio.toFixed(2)}` : "—"}</span></div>{!buy && <div className="mt-2 border-t border-[#252b34] pt-2 text-[9px] leading-4 text-amber-300"><b>{candidate.setupScore >= 70 ? "GOOD SETUP — ENTRY BLOCKED: " : "NOT READY: "}</b>{blockedReason}</div>}</div>; })}</div></section>;
}
function NoBuy({ result }: { result?: MarketScanResult }) { return <section className="border border-amber-500/30 bg-amber-500/[.06] p-8 text-center"><ShieldAlert size={28} className="mx-auto text-amber-400"/><div className="mt-3 text-3xl font-black text-amber-400">NO BUY RIGHT NOW</div><p className="mx-auto mt-3 max-w-2xl text-[12px] leading-6 text-[#aab2be]">{result?.rationale ?? "The scan completed without a qualified setup."} Waiting is the recommendation when no market passes confirmation and risk checks.</p></section>; }
function ScanLoading() { return <section className="border border-blue-500/20 bg-blue-500/[.04] p-8 text-center"><RefreshCw size={24} className="mx-auto animate-spin text-blue-400"/><b className="mt-3 block text-base">Scanning all configured markets…</b><p className="mt-2 text-[11px] text-[#687180]">Checking trend, location, closed-candle confirmation, and risk/reward.</p></section>; }
