"use client";
import { useMemo, useState } from "react";
import { Search, Star, X } from "lucide-react";
import { formatPrice, type MarketAsset } from "@/lib/market-data";
import type { DataSourceKind, Quote } from "@/lib/market-data/types";
import { useBatchQuotes } from "@/hooks/use-market-data";
type WatchQuote = Quote & { source: DataSourceKind; provider: string };
export function Watchlist({ assets, selected, onSelect, onRemove }: { assets: MarketAsset[]; selected: string; onSelect: (asset: MarketAsset) => void; onRemove: (asset: MarketAsset) => void }) {
  const [query, setQuery] = useState(""); const requestable = useMemo(() => assets.filter((asset) => asset.dataStatus !== "UNAVAILABLE"), [assets]); const quotes = useBatchQuotes(requestable); const data = quotes.data as Record<string, WatchQuote> | undefined;
  const visible = useMemo(() => { const text = query.toLowerCase().replace(/[\s/]/g, ""); return text ? assets.filter((asset) => `${asset.symbol}${asset.name}`.toLowerCase().replace(/[\s/]/g, "").includes(text)) : assets; }, [assets, query]);
  return <aside className="hidden w-[240px] shrink-0 flex-col bg-[#0c0f14] lg:flex"><div className="flex h-9 items-center justify-between border-b border-[#20242d] px-3"><span className="text-[10px] font-bold tracking-[.16em] text-[#89919e]">MY WATCHLIST</span><span className="text-[9px] text-[#565e6d]">{assets.length}</span></div><label className="relative m-2"><Search size={13} className="absolute left-2.5 top-2.5 text-[#596170]"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter favorites" className="h-8 w-full border border-[#252b35] bg-[#0a0d12] pl-8 pr-7 text-[10px] outline-none focus:border-blue-500/60"/>{query && <button onClick={() => setQuery("")} className="absolute right-1.5 top-1.5 grid size-5 place-items-center"><X size={11}/></button>}</label><div className="grid grid-cols-[1fr_auto] border-b border-[#20242d] px-3 py-2 text-[9px] uppercase text-[#565e6d]"><span>Symbol</span><span>Last / Change</span></div><div className="overflow-y-auto thin-scrollbar">{visible.map((asset) => { const quote = data?.[asset.symbol]; return <div key={`${asset.category}:${asset.symbol}`} className={`group relative border-b border-[#181c23] border-l-2 ${selected === asset.symbol ? "border-l-blue-500 bg-[#121821]" : "border-l-transparent"}`}><button onClick={() => onSelect(asset)} disabled={asset.dataStatus === "UNAVAILABLE"} className="grid w-full grid-cols-[1fr_auto] items-center px-3 py-3 text-left hover:bg-[#131820] disabled:cursor-not-allowed"><span className="min-w-0"><b className="block truncate text-[11px] text-[#d9dee7]">{asset.symbol}</b><small className="mt-1 block text-[8px] text-[#596170]">{asset.dataStatus === "UNAVAILABLE" ? "UNAVAILABLE" : quote?.source === "LIVE" ? `LIVE • ${quote.provider}` : quote?.source === "MOCK" ? "MOCK DATA" : ""}</small></span><span className="text-right font-mono"><b className="block text-[10px] text-[#bfc5cf]">{quote ? formatPrice(asset, quote.price) : quotes.isPending && asset.dataStatus !== "UNAVAILABLE" ? <span className="inline-block h-2 w-12 animate-pulse bg-[#252b35]"/> : "Unavailable"}</b><small className={`mt-1 block text-[9px] ${quote?.changePercent !== undefined && quote.changePercent >= 0 ? "text-[#16c784]" : "text-[#ea3943]"}`}>{quote ? `${quote.changePercent >= 0 ? "+" : ""}${quote.changePercent.toFixed(2)}%` : quotes.isError ? "Unavailable" : ""}</small></span></button><button onClick={() => onRemove(asset)} className="absolute right-1 top-1 hidden text-amber-400 group-hover:block"><Star size={10} fill="currentColor"/></button></div>; })}{!visible.length && <div className="p-6 text-center text-[9px] text-[#596170]">No favorites. Add instruments from Markets.</div>}</div></aside>;
}
