import type { PatternName } from "./types";

export const explanations: Record<PatternName, string> = {
  "Bullish Engulfing": "Buyers completely covered the previous bearish candle body, showing a strong shift toward buying pressure.",
  "Bearish Engulfing": "Sellers completely covered the previous bullish candle body, showing a strong shift toward selling pressure.",
  Hammer: "Sellers pushed price lower, but buyers recovered most of the move before the candle closed.",
  "Inverted Hammer": "Buyers tested higher prices after a decline, though follow-through is still needed.",
  "Morning Star": "A bearish move stalled in indecision and was followed by a strong bullish recovery.",
  "Three White Soldiers": "Three sustained bullish candles show persistent buying pressure.",
  "Bullish Marubozu": "Buyers controlled almost the entire candle with very little rejection.",
  "Shooting Star": "Buyers pushed higher, but sellers rejected the move and forced price back down.",
  "Hanging Man": "A deep selloff was recovered, but the long lower wick warns that support may be weakening after an advance.",
  "Evening Star": "A bullish move stalled in indecision and was followed by a strong bearish reversal.",
  "Three Black Crows": "Three sustained bearish candles show persistent selling pressure.",
  "Bearish Marubozu": "Sellers controlled almost the entire candle with very little rejection.",
  Doji: "Open and close are very close. Buyers and sellers are balanced and direction is unclear.",
  "Spinning Top": "A small body with wicks on both sides shows hesitation and weak directional control.",
  "Long-Legged Doji": "Strong movement in both directions ended near the open, showing pronounced uncertainty.",
  "Dragonfly Doji": "A long lower rejection closed near the high, showing buyers regained control after a selloff.",
  "Gravestone Doji": "A long upper rejection closed near the low, showing sellers regained control after a rally.",
  "Inside Bar": "Price contracted inside the previous range and is consolidating before a possible expansion.",
  "Outside Bar": "Price expanded beyond both sides of the prior range, showing a sharp volatility increase.",
  "Rising Three Methods": "A controlled pullback remained inside a bullish impulse before buyers resumed control.",
  "Falling Three Methods": "A controlled bounce remained inside a bearish impulse before sellers resumed control.",
  "Long Lower Wick": "Lower prices were rejected as buyers pushed the close away from the candle low.",
  "Long Upper Wick": "Higher prices were rejected as sellers pushed the close away from the candle high.",
  "Bullish Pin Bar": "A very long lower wick and compact body show a decisive rejection of lower prices.",
  "Bearish Pin Bar": "A very long upper wick and compact body show a decisive rejection of higher prices.",
  "Piercing Line": "A bullish candle recovered more than half of the prior bearish body, signaling a possible reversal.",
  "Dark Cloud Cover": "A bearish candle erased more than half of the prior bullish body, signaling a possible reversal.",
  "Bullish Harami": "A smaller bullish body formed inside a large bearish body as selling pressure contracted.",
  "Bearish Harami": "A smaller bearish body formed inside a large bullish body as buying pressure contracted.",
  "Tweezer Bottom": "Two candles rejected approximately the same low before buyers took control.",
  "Tweezer Top": "Two candles rejected approximately the same high before sellers took control.",
  "Three Inside Up": "A bullish harami received third-candle confirmation above the original bearish body.",
  "Three Inside Down": "A bearish harami received third-candle confirmation below the original bullish body.",
  "Abandoned Baby Bullish": "An isolated doji below the prior move was followed by a bullish gap and recovery.",
  "Abandoned Baby Bearish": "An isolated doji above the prior move was followed by a bearish gap and decline.",
  "Bullish Liquidity Sweep": "Price ran below recent lows to collect liquidity, then reclaimed the swept level before closing.",
  "Bearish Liquidity Sweep": "Price ran above recent highs to collect liquidity, then rejected the swept level before closing.",
  "Bullish False Breakout": "Price briefly broke support but reclaimed the entire zone before the candle closed.",
  "Bearish False Breakout": "Price briefly broke resistance but fell back below the entire zone before the candle closed.",
};
