import { nearestZones, type MultiTimeframePatternAnalysis, type MultiTimeframeStructureAnalysis, type PatternDetection } from "@/lib/analysis";
import type { MarketSymbol, Quote } from "@/lib/market-data/types";
import type { NewsRiskAssessment } from "@/lib/news";
import type { DirectionalScore, PriceZoneFact, RuleBasedSetup, ScoreComponentDetail, SetupLocation, SetupQuality, SetupScoreComponents, TradingPreference } from "./types";

export type SetupEngineInput = { asset: MarketSymbol; quote: Quote; structure: MultiTimeframeStructureAnalysis; patterns: MultiTimeframePatternAnalysis; newsRisk?: NewsRiskAssessment | null };
export type SetupThresholds = { actionScore: number; minimumEdge: number; minimumRiskReward: number };
export const defaultThresholds: SetupThresholds = { actionScore: 70, minimumEdge: 15, minimumRiskReward: 1.2 };
const stableHash = (value: string) => { let hash = 2166136261; for (let index = 0; index < value.length; index++) { hash ^= value.charCodeAt(index); hash = Math.imul(hash, 16777619); } return (hash >>> 0).toString(16).padStart(8, "0"); };
const zoneFact = (zone?: { low: number; high: number; midpoint: number; strength: number; touches: number }): PriceZoneFact | null => zone ? { low: zone.low, high: zone.high, midpoint: zone.midpoint, strength: zone.strength, touches: zone.touches } : null;
const quality = (score: number): SetupQuality => score >= 90 ? "Very Strong" : score >= 80 ? "Strong" : score >= 70 ? "Good" : score >= 60 ? "Moderate" : score >= 50 ? "Developing" : "Weak";
const legacyLabel = (score: number, preference: TradingPreference): RuleBasedSetup["confidenceLabel"] => preference === "WAIT" ? score >= 60 ? "Weak / caution" : "Wait" : score >= 80 ? "Strong setup" : "Good setup";
const strongest = (patterns: PatternDetection[], direction: "bullish" | "bearish") => patterns.filter((pattern) => pattern.direction === direction).sort((a, b) => Number(b.status === "confirmed") - Number(a.status === "confirmed") || b.confidence - a.confidence)[0] ?? null;
const detail = (category: string, pointsAwarded: number, maxPoints: number, reason: string): ScoreComponentDetail => ({ category, pointsAwarded: Math.max(0, Math.min(maxPoints, Math.round(pointsAwarded))), maxPoints, reason });
const directional = (items: ScoreComponentDetail[]): DirectionalScore => { const components: SetupScoreComponents = { trend4H: items[0].pointsAwarded, location1H: items[1].pointsAwarded, confirmation15M: items[2].pointsAwarded, patternQuality: items[3].pointsAwarded, riskReward: items[4].pointsAwarded, marketClarity: items[5].pointsAwarded }; return { components, breakdown: items, total: Object.values(components).reduce((sum, value) => sum + value, 0) }; };
const rrPoints = (ratio: number | null) => ratio === null || ratio < 1 ? 0 : ratio < 1.2 ? 2 : ratio < 1.5 ? 4 : ratio < 2 ? 6 : ratio < 3 ? 8 : 10;
function validRatio(direction: "buy" | "sell", entry: number, stop: number | null, target: number | null) { if (stop === null || target === null || ![entry, stop, target].every((value) => Number.isFinite(value) && value > 0)) return null; if (direction === "buy" && !(target > entry && entry > stop)) return null; if (direction === "sell" && !(stop > entry && entry > target)) return null; return Number((Math.abs(target - entry) / Math.abs(entry - stop)).toFixed(2)); }

export function calculateSetup(input: SetupEngineInput, thresholds: SetupThresholds = defaultThresholds): RuleBasedSetup {
  const { asset, quote, structure, patterns, newsRisk: incomingNewsRisk } = input; const h4 = structure.byTimeframe["4H"]; const h1 = structure.byTimeframe["1H"]; const m15 = structure.byTimeframe["15m"]; const nearest = h1 ? nearestZones(h1.zones.filter((zone) => zone.touches >= 2), quote.price) : { support: undefined, resistance: undefined }; const support = zoneFact(nearest.support); const resistance = zoneFact(nearest.resistance); const tolerance = quote.price * .0015; const atSupport = !!support && quote.price >= support.low - tolerance && quote.price <= support.high + tolerance; const atResistance = !!resistance && quote.price >= resistance.low - tolerance && quote.price <= resistance.high + tolerance; const reversal = h1?.roleReversals[0] ?? null;
  let location: SetupLocation = atSupport ? "support" : atResistance ? "resistance" : "middle"; if (reversal) location = "retest";
  const recentPatterns = [...(patterns.byTimeframe["15m"]?.patterns ?? []), ...(patterns.byTimeframe["1H"]?.patterns ?? [])]; const bullish = strongest(recentPatterns, "bullish"); const bearish = strongest(recentPatterns, "bearish");
  const m15Patterns = patterns.byTimeframe["15m"]?.patterns ?? [];
  const formingPattern = m15Patterns.find((pattern) => pattern.status === "forming") ?? null;
  const latestClosedPattern = m15Patterns.find((pattern) => pattern.status === "confirmed" && pattern.timestamp === m15?.analyzedThrough) ?? null;
  const confirmation = latestClosedPattern ?? formingPattern;
  const confirmed = !!latestClosedPattern && latestClosedPattern.direction !== "neutral";
  const forming = !latestClosedPattern && !!formingPattern;
  const trend = h4?.trend.trend ?? "sideways"; const trendConfidence = h4?.trend.confidence ?? 0; const clarity = trend === "sideways" || !h4 || !h1 ? 1 : h4.trend.trend === h1.trend.trend ? 5 : 2;
  const buyStop = support ? support.low * .999 : null; const buyTarget = resistance?.midpoint ?? null; const sellStop = resistance ? resistance.high * 1.001 : null; const sellTarget = support?.midpoint ?? null; const buyRatio = validRatio("buy", quote.price, buyStop, buyTarget); const sellRatio = validRatio("sell", quote.price, sellStop, sellTarget);
  const trendDetail = (direction: "bullish" | "bearish") => detail("4H Trend", trend === direction ? 25 * trendConfidence / 100 : trend === "sideways" ? 5 : 1, 25, trend === direction ? `${trendConfidence}% ${direction} 4H structure aligns` : trend === "sideways" ? "4H structure is mixed/sideways" : `4H structure opposes ${direction}`);
  const locationDetail = (direction: "bullish" | "bearish") => { const aligned = direction === "bullish" ? atSupport || reversal?.newType === "support" : atResistance || reversal?.newType === "resistance"; const opposed = direction === "bullish" ? atResistance : atSupport; const points = aligned ? reversal ? 25 : 23 : opposed ? 0 : 3; return detail("1H Setup", points, 25, aligned ? `${location} aligns with a ${direction} setup` : opposed ? `Price is at the opposing 1H zone` : "Price is in the middle of the 1H range"); };
  const confirmationDetail = (direction: "bullish" | "bearish") => { const aligned = confirmation?.direction === direction; const points = aligned ? confirmation!.status === "confirmed" ? 20 * confirmation!.confidence / 100 : Math.min(6, 6 * confirmation!.confidence / 100) : 0; return detail("15M Confirmation", points, 20, !confirmation ? "15M confirmation is missing" : aligned ? `${confirmation.status} ${confirmation.name}` : `15M confirmation does not support ${direction}`); };
  const patternDetail = (direction: "bullish" | "bearish", pattern: PatternDetection | null) => { if (!pattern) return detail("Pattern", 0, 15, `No recent ${direction} pattern`); const correctLocation = direction === "bullish" ? atSupport : atResistance; const contextMultiplier = correctLocation || location === "retest" ? 1 : .4; const statusMultiplier = pattern.status === "confirmed" ? 1 : .4; const trendMultiplier = pattern.againstMajorTrend ? .35 : 1; return detail("Pattern", 15 * pattern.confidence / 100 * contextMultiplier * statusMultiplier * trendMultiplier, 15, `${pattern.status} ${pattern.name}${correctLocation ? " at the correct price zone" : " away from an ideal zone"}${pattern.againstMajorTrend ? ", against 4H trend" : ""}`); };
  const ratioDetail = (ratio: number | null) => detail("Risk / Reward", rrPoints(ratio), 10, ratio === null ? "Entry, stop, and target do not form a valid setup" : `Validated risk/reward is 1:${ratio.toFixed(2)}`);
  const clarityDetail = detail("Market Clarity", clarity, 5, clarity === 5 ? "4H and 1H direction agree" : clarity === 1 ? "Structure is mixed or incomplete" : "Timeframes are not fully aligned");
  const buyScore = directional([trendDetail("bullish"), locationDetail("bullish"), confirmationDetail("bullish"), patternDetail("bullish", bullish), ratioDetail(buyRatio), clarityDetail]); const sellScore = directional([trendDetail("bearish"), locationDetail("bearish"), confirmationDetail("bearish"), patternDetail("bearish", bearish), ratioDetail(sellRatio), clarityDetail]);
  const leading: TradingPreference = buyScore.total >= sellScore.total ? "BUY" : "SELL"; const leadingScore = Math.max(buyScore.total, sellScore.total); const edge = Math.abs(buyScore.total - sellScore.total); const leadingRatio = leading === "BUY" ? buyRatio : sellRatio; const leadingConfirmed = confirmed && confirmation?.direction === (leading === "BUY" ? "bullish" : "bearish"); let technicalPreference: TradingPreference = leading;
  if (leadingScore < thresholds.actionScore || edge < thresholds.minimumEdge || !leadingConfirmed || leadingRatio === null || leadingRatio < thresholds.minimumRiskReward) technicalPreference = "WAIT";
  const newsRisk = incomingNewsRisk ?? { score: 0, label: "unavailable" as const, reasons: ["News context is not available"], technicalPenalty: 0, upcomingEvents: [], relevantBreakingNews: [], nextMajorEvent: null, assessedAt: Date.now() }; const technicalSetupScore = leadingScore; const setupScore = Math.max(0, technicalSetupScore - newsRisk.technicalPenalty); let preference = technicalPreference; if (newsRisk.label === "high" || setupScore < thresholds.actionScore) preference = "WAIT";
  const chosenDirection: "buy" | "sell" = leading === "BUY" ? "buy" : "sell"; const chosenRatio = chosenDirection === "buy" ? buyRatio : sellRatio; const chosenStop = chosenDirection === "buy" ? buyStop : sellStop; const chosenTarget = chosenDirection === "buy" ? buyTarget : sellTarget; const riskReward: RuleBasedSetup["riskReward"] = { direction: chosenRatio === null ? "none" : chosenDirection, entry: quote.price, stop: chosenStop, target: chosenTarget, ratio: chosenRatio, valid: chosenRatio !== null, reason: chosenRatio === null ? "A valid entry, stop, and target are not available" : `Validated ${chosenDirection.toUpperCase()} geometry` };
  const ruleReasons = [`4H trend is ${trend} with ${trendConfidence}% structure confidence`, `BUY score ${buyScore.total}; SELL score ${sellScore.total}`, confirmation ? `15M ${confirmation.name} is ${confirmation.status}` : "15M confirmation is missing", riskReward.valid ? `Risk/reward is 1:${riskReward.ratio!.toFixed(2)}` : "Risk/reward is unavailable", ...(newsRisk.label === "high" ? [`Technical setup is ${technicalPreference}, but major relevant news is too close`] : [])];
  const ruleWarnings = [trend === "sideways" ? "Higher-timeframe structure is sideways" : null, !leadingConfirmed ? "Directional 15M confirmation is not complete" : null, leadingRatio === null ? "Risk/reward is unavailable" : leadingRatio < thresholds.minimumRiskReward ? "Risk/reward is below the configured minimum" : null, edge < thresholds.minimumEdge ? "BUY and SELL scores are too close" : null, newsRisk.label === "high" ? `${newsRisk.reasons[0]} · volatility may invalidate the setup` : newsRisk.label === "medium" ? `${newsRisk.reasons[0]} · ${newsRisk.technicalPenalty}-point news adjustment` : newsRisk.label === "unavailable" ? "News context is temporarily unavailable; no news penalty was applied" : null].filter((item): item is string => !!item);
  const buyConditions = ["A confirmed bullish 15M pattern or mini swing break", resistance ? `A hold above ${resistance.high} followed by a successful retest` : "A confirmed breakout and retest", "Validated risk/reward of at least 1:1.2"];
  const sellConditions = ["A confirmed bearish 15M rejection or mini swing break", support ? `A confirmed break below ${support.low} followed by a failed retest` : "A confirmed bearish break and retest", "Validated risk/reward of at least 1:1.2"];
  const invalidationFacts = [chosenDirection === "buy" && support ? `A confirmed close below ${support.low}` : chosenDirection === "sell" && resistance ? `A confirmed close above ${resistance.high}` : "Loss of the current 1H structure", "A new opposing 15M confirmation"];
  const watchFacts = [resistance ? `Reaction at resistance ${resistance.low}–${resistance.high}` : "Formation of confirmed resistance", support ? `Hold around support ${support.low}–${support.high}` : "Formation of confirmed support", "The next confirmed 15M candle"];
  const structureLabels = h4?.latestStructure.includes(" + ") ? h4.latestStructure.split(" + ") : [h4?.latestStructure ?? "Insufficient structure"]; const stateKey = stableHash(JSON.stringify({ symbol: asset.symbol, h4: h4?.analyzedThrough, h1: h1?.analyzedThrough, m15: m15?.analyzedThrough, trend, location, confirmation: confirmation ? [confirmation.id, confirmation.status] : null, buy: buyScore.total, sell: sellScore.total, rr: [buyRatio, sellRatio], news: [newsRisk.label, newsRisk.technicalPenalty, newsRisk.nextMajorEvent?.id, newsRisk.relevantBreakingNews.map((article) => article.id).slice(0, 3)] }));
  return { symbol: asset.symbol, category: asset.category, price: quote.price, calculatedAt: Date.now(), stateKey, trend4H: { direction: trend, confidence: trendConfidence, structure: structureLabels }, setup1H: { location, structure: h1?.latestStructure ?? "Insufficient structure", support, resistance, roleReversal: reversal?.label ?? null }, confirmation15M: { direction: confirmation?.direction ?? "none", confirmed, forming: !!forming, pattern: confirmation?.name ?? null, score: confirmation?.confidence ?? 0 }, patterns: { bullish: bullish ? { name: bullish.name, score: bullish.confidence, status: bullish.status } : null, bearish: bearish ? { name: bearish.name, score: bearish.confidence, status: bearish.status } : null }, riskReward, buyScore, sellScore, technicalPreference, technicalSetupScore, preference, setupScore, setupQuality: quality(setupScore), confidenceLabel: legacyLabel(setupScore, preference), newsRisk: { score: newsRisk.score, label: newsRisk.label, reasons: newsRisk.reasons, technicalPenalty: newsRisk.technicalPenalty, upcomingEvent: newsRisk.nextMajorEvent ? { id: newsRisk.nextMajorEvent.id, title: newsRisk.nextMajorEvent.title, timestamp: newsRisk.nextMajorEvent.timestamp, impact: newsRisk.nextMajorEvent.impact } : null, relevantHeadlineIds: newsRisk.relevantBreakingNews.map((article) => article.id) }, ruleReasons, ruleWarnings, buyConditions, sellConditions, invalidationFacts, watchFacts };
}
const setupCache = new Map<string, RuleBasedSetup>();
export function memoizedCalculateSetup(input: SetupEngineInput, thresholds: SetupThresholds = defaultThresholds) { const candidate = calculateSetup(input, thresholds); const cached = setupCache.get(candidate.stateKey); if (cached) return cached; setupCache.set(candidate.stateKey, candidate); if (setupCache.size > 100) setupCache.delete(setupCache.keys().next().value!); return candidate; }
